#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var docopt, sh, cat, fs, vex, doc, getOption, o, filename, content;
  docopt = require('docopt').docopt;
  cat = (sh = require('shelljs')).cat;
  fs = require('fs');
  vex = require('verbal-expressions');
  doc = "Usage:\n    stupid-replace TAG -f FILE\n    stupid-replace -h | --help \n\nOptions:\n    -f, --file FILE     If no <input> is passed, it is read from stdin";
  getOption = function(a, b, def, o){
    if (!o[a] && !o[b]) {
      return def;
    } else {
      return o[b];
    }
  };
  o = docopt(doc);
  filename = getOption('-f', '--file', '/dev/stdin', o);
  content = cat(filename);
  fs.readFile('/dev/stdin', 'utf-8', function(err, data){
    var exp;
    if (!err) {
      exp = vex().then(o['TAG']);
      return console.log(data.replace(exp, content));
    }
  });
}).call(this);
